# Site settings
title: Explore DataGouv
email: paul-antoine.chevalier@data.gouv.fr
description: > # this means to ignore newlines until "baseurl:"
  un blog pour explorer les données de data.gouv
url: "http://example.com" # the base hostname & protocol for your site
twitter_username: pa_chevalier
github_username:  pachevalier
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
exclude: ['*.Rmd']
